import { FilmRecipe } from '../types';

export const FILM_RECIPES: FilmRecipe[] = [
  // ==========================================
  // ⭐ TOPP 2025 & HYLLADE FAVORITER
  // ==========================================
  {
    id: 'classic-cuban-negative',
    name: 'Classic Cuban Negative',
    shortCode: 'CCN',
    year: '2024',
    author: 'Osan Bilgi',
    category: 'featured',
    baseFilm: 'Classic Negative (DR400)',
    description: 'Osan Bilgis virala recept: Varm gyllene Kubansk eftermiddagssol, mjuk drömsk lyster (Clarity -4), rika skuggor med subtil grön skugga och kraftigt organiskt korn.',
    contrast: 1.22,
    exposure: 0.08,
    highlights: -0.35, // Highlight -2
    shadows: 0.28,    // Shadow +1
    saturation: 1.28, // Color +4
    colorMatrix: [
      1.14, -0.04, -0.04,
      -0.06, 1.10, -0.04,
      -0.08, 0.12, 0.90
    ],
    wbShift: { r: 0.16, b: -0.20 }, // Auto WB +4R / -5B
    grainAmount: 0.36,
    grainRoughness: 0.65,
    bloomAmount: 0.32,
    halationAmount: 0.28,
  },
  {
    id: 'reggies-portra',
    name: "Reggie's Portra",
    shortCode: 'RP',
    year: '2025',
    author: 'Ritchie Roesch / Reggie Ballesteros',
    category: 'featured',
    baseFilm: 'Classic Chrome (DR400)',
    description: '#1 mest populära receptet 2025 på Fuji X Weekly. Varma pastelltoner, krämiga hudtoner och mjuk highlight roll-off för vardags- och gatufoto.',
    contrast: 1.04,
    exposure: 0.04,
    highlights: -0.15,
    shadows: -0.15,
    saturation: 1.10,
    colorMatrix: [
      1.06, -0.02, -0.04,
      -0.02, 1.04, -0.02,
      -0.04, 0.05, 0.94
    ],
    wbShift: { r: 0.06, b: -0.14 },
    grainAmount: 0.18,
    grainRoughness: 0.38,
    bloomAmount: 0.16,
    halationAmount: 0.18,
  },
  {
    id: 'kodachrome-64',
    name: 'Kodachrome 64',
    shortCode: 'K64',
    year: '1974',
    author: 'Fuji X Weekly',
    category: 'featured',
    baseFilm: 'Classic Chrome',
    description: 'Tidlös National Geographic-estetik från 70- & 80-talet; djup cyanblå himmel, mättade röda och gula toner och kraftfull kontrast.',
    contrast: 1.26,
    exposure: 0.0,
    highlights: 0.15,
    shadows: 0.30,
    saturation: 1.14,
    colorMatrix: [
      1.08, -0.02, -0.06,
      0.02, 1.02, -0.04,
      -0.08, 0.10, 0.98
    ],
    wbShift: { r: 0.08, b: -0.18 },
    grainAmount: 0.22,
    grainRoughness: 0.42,
    bloomAmount: 0.12,
    halationAmount: 0.16,
  },
  {
    id: 'vibrant-arizona',
    name: 'Vibrant Arizona',
    shortCode: 'VA',
    year: '2023',
    author: 'Fuji X Weekly',
    category: 'featured',
    baseFilm: 'Nostalgic Negative',
    description: 'Solmättad ökenmagi med intensiva terrakottatoner, turkos himmel och guldskimrande eftermiddagsljus (#3 på Fuji X Weekly).',
    contrast: 1.22,
    exposure: 0.02,
    highlights: -0.12,
    shadows: 0.20,
    saturation: 1.35,
    colorMatrix: [
      1.15, 0.02, -0.14,
      -0.03, 1.08, -0.04,
      -0.09, 0.08, 0.92
    ],
    wbShift: { r: 0.14, b: -0.22 },
    grainAmount: 0.34,
    grainRoughness: 0.58,
    bloomAmount: 0.24,
    halationAmount: 0.28,
  },
  {
    id: 'pacific-blues',
    name: 'Pacific Blues',
    shortCode: 'PB',
    year: '2023',
    author: 'Lucy Laucht & Ritchie Roesch',
    category: 'featured',
    baseFilm: 'Classic Negative',
    description: 'Kustnära sommarvibbar inspirerade av Lucy Laucht; djupaste Stilla Havs-teal, dämpad solblekning och rik kontrast.',
    contrast: 1.24,
    exposure: 0.06,
    highlights: -0.30,
    shadows: 0.35,
    saturation: 1.28,
    colorMatrix: [
      1.02, -0.04, 0.02,
      -0.06, 1.08, 0.02,
      -0.08, 0.20, 0.98
    ],
    wbShift: { r: 0.04, b: -0.10 },
    grainAmount: 0.32,
    grainRoughness: 0.55,
    bloomAmount: 0.26,
    halationAmount: 0.22,
  },
  {
    id: 'california-summer',
    name: 'California Summer',
    shortCode: 'CS',
    year: '2024',
    author: 'Preet & Ritchie Roesch',
    category: 'featured',
    baseFilm: 'Nostalgic Negative',
    description: 'Gyllene Stillahavskust med mjuka pasteller, upplyfta skuggor och mjuk disig sommarglöd.',
    contrast: 1.02,
    exposure: 0.10,
    highlights: -0.32,
    shadows: -0.15,
    saturation: 1.30,
    colorMatrix: [
      1.12, 0.02, -0.10,
      -0.02, 1.06, -0.02,
      -0.06, 0.08, 0.90
    ],
    wbShift: { r: -0.04, b: -0.24 },
    grainAmount: 0.20,
    grainRoughness: 0.40,
    bloomAmount: 0.34,
    halationAmount: 0.25,
  },

  // ==========================================
  // 🎞️ KODAK EMULSIONER
  // ==========================================
  {
    id: 'portra-400-v2',
    name: 'Kodak Portra 400 v2',
    shortCode: 'P400-II',
    year: 'Modern',
    author: 'Fuji X Weekly',
    category: 'kodak',
    baseFilm: 'Classic Chrome',
    description: 'Förfinad modern version av legendariska Portra 400 med perfekta varma hudtoner och mjukaste highlight roll-off.',
    contrast: 1.02,
    exposure: 0.06,
    highlights: -0.20,
    shadows: -0.25,
    saturation: 1.08,
    colorMatrix: [
      1.08, -0.02, -0.06,
      -0.02, 1.04, -0.02,
      -0.05, 0.04, 0.92
    ],
    wbShift: { r: 0.09, b: -0.15 },
    grainAmount: 0.20,
    grainRoughness: 0.42,
    bloomAmount: 0.20,
    halationAmount: 0.24,
  },
  {
    id: 'kodak-gold-200',
    name: 'Kodak Gold 200',
    shortCode: 'G200',
    year: '1988',
    author: 'Fuji X Weekly',
    category: 'kodak',
    baseFilm: 'Classic Chrome',
    description: 'Nostalgisk 90-talskänsla med varma gyllengula stick, rika gröna blad och äkta semesterkänsla.',
    contrast: 1.18,
    exposure: 0.02,
    highlights: -0.12,
    shadows: 0.18,
    saturation: 1.22,
    colorMatrix: [
      1.10, 0.00, -0.08,
      -0.02, 1.05, -0.02,
      -0.07, 0.06, 0.88
    ],
    wbShift: { r: 0.12, b: -0.16 },
    grainAmount: 0.28,
    grainRoughness: 0.50,
    bloomAmount: 0.18,
    halationAmount: 0.22,
  },
  {
    id: 'portra-800-v3',
    name: 'Kodak Portra 800 v3',
    shortCode: 'P800',
    year: '1998',
    author: 'Fuji X Weekly',
    category: 'kodak',
    baseFilm: 'Classic Chrome',
    description: 'Högkänslig analog film med markant korn, fyllig färgmättnad och gyllene toner vid skymning och lampljus.',
    contrast: 1.14,
    exposure: 0.03,
    highlights: -0.15,
    shadows: 0.10,
    saturation: 1.20,
    colorMatrix: [
      1.09, -0.01, -0.06,
      -0.03, 1.05, -0.02,
      -0.06, 0.05, 0.90
    ],
    wbShift: { r: 0.12, b: -0.18 },
    grainAmount: 0.34,
    grainRoughness: 0.60,
    bloomAmount: 0.22,
    halationAmount: 0.26,
  },
  {
    id: 'mccurry-kodachrome',
    name: 'McCurry Kodachrome',
    shortCode: 'MC-K',
    year: '1985',
    author: 'Steve McCurry Style',
    category: 'kodak',
    baseFilm: 'Classic Chrome',
    description: 'Inspirerad av Steve McCurrys National Geographic-fotografier: mättade primärfärger och djup dramatisk kontrast.',
    contrast: 1.32,
    exposure: -0.02,
    highlights: 0.22,
    shadows: 0.35,
    saturation: 1.25,
    colorMatrix: [
      1.12, -0.04, -0.04,
      -0.02, 1.08, -0.04,
      -0.08, 0.10, 0.96
    ],
    wbShift: { r: 0.12, b: -0.16 },
    grainAmount: 0.24,
    grainRoughness: 0.45,
    bloomAmount: 0.15,
    halationAmount: 0.20,
  },
  {
    id: 'vintage-kodachrome',
    name: 'Vintage Kodachrome',
    shortCode: 'V-K64',
    year: '1960s',
    author: 'Fuji X Weekly',
    category: 'kodak',
    baseFilm: 'Classic Chrome',
    description: 'Blekta diabilder från 1950- och 60-talet med gulaktiga högdagrar och mjuk nostalgisk värme.',
    contrast: 1.16,
    exposure: 0.04,
    highlights: 0.12,
    shadows: 0.15,
    saturation: 0.95,
    colorMatrix: [
      1.10, 0.02, -0.10,
      0.00, 1.04, -0.04,
      -0.08, 0.08, 0.88
    ],
    wbShift: { r: 0.12, b: -0.18 },
    grainAmount: 0.26,
    grainRoughness: 0.48,
    bloomAmount: 0.22,
    halationAmount: 0.24,
  },
  {
    id: 'classic-color',
    name: 'Classic Color',
    shortCode: 'CCLR',
    year: '1970s',
    author: 'Fuji X Weekly',
    category: 'kodak',
    baseFilm: 'Classic Chrome',
    description: 'Vintage trycksakskänsla från 70-talets magasin med varmt pappersvitt och dämpad cyan.',
    contrast: 1.16,
    exposure: 0.02,
    highlights: 0.05,
    shadows: 0.20,
    saturation: 1.15,
    colorMatrix: [
      1.08, 0.00, -0.06,
      -0.02, 1.04, -0.02,
      -0.06, 0.08, 0.92
    ],
    wbShift: { r: 0.08, b: -0.08 },
    grainAmount: 0.25,
    grainRoughness: 0.46,
    bloomAmount: 0.16,
    halationAmount: 0.18,
  },

  // ==========================================
  // 📷 FUJIFILM ORIGINAL & FÄRGFILM
  // ==========================================
  {
    id: 'fujifilm-negative',
    name: 'Fujifilm Negative (Superia)',
    shortCode: 'F-NEG',
    year: '1998',
    author: 'Fuji X Weekly',
    category: 'fuji',
    baseFilm: 'Classic Negative',
    description: 'Äkta 90-tals färgfilm från snabbköpet med distinkta gröna och magenta skiftningar och krispig kontrast.',
    contrast: 1.26,
    exposure: 0.0,
    highlights: 0.05,
    shadows: 0.30,
    saturation: 1.15,
    colorMatrix: [
      1.06, -0.04, 0.00,
      -0.08, 1.09, 0.00,
      -0.06, 0.12, 0.94
    ],
    wbShift: { r: 0.05, b: -0.08 },
    grainAmount: 0.28,
    grainRoughness: 0.54,
    bloomAmount: 0.18,
    halationAmount: 0.22,
  },
  {
    id: 'universal-negative',
    name: 'Universal Negative',
    shortCode: 'U-NEG',
    year: '2022',
    author: 'Fuji X Weekly',
    category: 'fuji',
    baseFilm: 'Classic Negative',
    description: 'En mjukare och mer mångsidig version av Classic Negative, anpassad för både porträtt och gatufoto.',
    contrast: 1.15,
    exposure: 0.02,
    highlights: -0.15,
    shadows: 0.10,
    saturation: 1.05,
    colorMatrix: [
      1.04, -0.03, 0.00,
      -0.04, 1.05, 0.00,
      -0.04, 0.08, 0.96
    ],
    wbShift: { r: 0.04, b: -0.04 },
    grainAmount: 0.24,
    grainRoughness: 0.45,
    bloomAmount: 0.16,
    halationAmount: 0.18,
  },
  {
    id: 'reala-ace',
    name: 'Reala Ace',
    shortCode: 'RA',
    year: '2024',
    author: 'Fujifilm Official',
    category: 'fuji',
    baseFilm: 'Fujicolor Reala Ace 100',
    description: 'Fujifilms hyllade profil med 4:e färglagret (cyan); naturtrogen precision med mjuka och rika färgtoner.',
    contrast: 1.05,
    exposure: 0.0,
    highlights: 0.0,
    shadows: 0.05,
    saturation: 1.05,
    colorMatrix: [
      1.02, 0.00, -0.02,
      0.00, 1.02, 0.00,
      -0.02, 0.02, 1.02
    ],
    wbShift: { r: 0.0, b: 0.0 },
    grainAmount: 0.14,
    grainRoughness: 0.32,
    bloomAmount: 0.10,
    halationAmount: 0.10,
  },
  {
    id: 'easy-reala-ace',
    name: 'Easy Reala Ace',
    shortCode: 'E-RA',
    year: '2024',
    author: 'Fuji X Weekly',
    category: 'fuji',
    baseFilm: 'Reala / Provia',
    description: 'Enkel allround-färgprofil för daglig fotografering med levande och ren färgåtergivning.',
    contrast: 1.08,
    exposure: 0.02,
    highlights: -0.10,
    shadows: 0.15,
    saturation: 1.08,
    colorMatrix: [
      1.03, 0.00, -0.01,
      0.00, 1.02, 0.00,
      -0.02, 0.02, 1.01
    ],
    wbShift: { r: 0.03, b: 0.0 },
    grainAmount: 0.16,
    grainRoughness: 0.35,
    bloomAmount: 0.12,
    halationAmount: 0.12,
  },
  {
    id: 'pro-negative-160c',
    name: 'PRO Negative 160C',
    shortCode: 'P160C',
    year: '2004',
    author: 'Fuji X Weekly',
    category: 'fuji',
    baseFilm: 'Fujicolor PRO 160C',
    description: 'Professionell analog studiofilm för mode och porträtt; svala skuggor, neutral hud och ren färgskärpa.',
    contrast: 1.12,
    exposure: 0.02,
    highlights: 0.10,
    shadows: -0.10,
    saturation: 0.98,
    colorMatrix: [
      0.98, 0.02, 0.00,
      0.00, 0.99, 0.02,
      0.00, 0.02, 1.02
    ],
    wbShift: { r: -0.03, b: 0.04 },
    grainAmount: 0.15,
    grainRoughness: 0.34,
    bloomAmount: 0.12,
    halationAmount: 0.10,
  },
  {
    id: 'classic-chrome',
    name: 'Classic Chrome',
    shortCode: 'CC',
    year: '1970s',
    author: 'Fujifilm Official',
    category: 'fuji',
    baseFilm: 'Kodachrome Style',
    description: 'Dokumentär look med dämpade toner, djupa skuggor och subtil cyan himmelsförskjutning.',
    contrast: 1.15,
    exposure: 0.0,
    highlights: -0.2,
    shadows: 0.3,
    saturation: 0.82,
    colorMatrix: [
      0.95, 0.05, 0.00,
      0.02, 0.88, 0.10,
      -0.05, 0.15, 0.90
    ],
    wbShift: { r: 0.04, b: -0.06 },
    grainAmount: 0.22,
    grainRoughness: 0.45,
    bloomAmount: 0.12,
    halationAmount: 0.15,
  },
  {
    id: 'classic-negative',
    name: 'Classic Negative',
    shortCode: 'NC',
    year: '1980s',
    author: 'Fujifilm Official',
    category: 'fuji',
    baseFilm: 'Superia 400',
    description: 'Hög kontrast med gröna/teal skuggor och varma persikofärgade högdagrar.',
    contrast: 1.25,
    exposure: -0.05,
    highlights: 0.2,
    shadows: 0.4,
    saturation: 0.95,
    colorMatrix: [
      1.05, -0.05, 0.00,
      -0.08, 1.08, 0.00,
      -0.05, 0.12, 0.93
    ],
    wbShift: { r: 0.08, b: -0.08 },
    grainAmount: 0.28,
    grainRoughness: 0.55,
    bloomAmount: 0.18,
    halationAmount: 0.24,
  },
  {
    id: 'velvia-vivid',
    name: 'Velvia / Vivid',
    shortCode: 'VV',
    year: '1990',
    author: 'Fujifilm Official',
    category: 'fuji',
    baseFilm: 'Fujichrome Velvia 50',
    description: 'Ultramättade färger, djupblå himmel, intensiv grönska och skarp kontrast för landskap.',
    contrast: 1.22,
    exposure: 0.05,
    highlights: 0.1,
    shadows: 0.2,
    saturation: 1.38,
    colorMatrix: [
      1.10, -0.05, -0.05,
      -0.05, 1.15, -0.10,
      -0.02, -0.08, 1.10
    ],
    wbShift: { r: 0.02, b: 0.02 },
    grainAmount: 0.15,
    grainRoughness: 0.35,
    bloomAmount: 0.10,
    halationAmount: 0.12,
  },
  {
    id: 'provia-standard',
    name: 'Provia / Standard',
    shortCode: 'STD',
    year: '2000',
    author: 'Fujifilm Official',
    category: 'fuji',
    baseFilm: 'Fujichrome Provia 100F',
    description: 'Perfekt balanserad färgprofil med naturliga hudtoner och mjukt dynamiskt omfång.',
    contrast: 1.0,
    exposure: 0.0,
    highlights: 0.0,
    shadows: 0.0,
    saturation: 1.0,
    colorMatrix: [
      1.0, 0.0, 0.0,
      0.0, 1.0, 0.0,
      0.0, 0.0, 1.0
    ],
    wbShift: { r: 0.0, b: 0.0 },
    grainAmount: 0.14,
    grainRoughness: 0.35,
    bloomAmount: 0.08,
    halationAmount: 0.08,
  },
  {
    id: 'astia-soft',
    name: 'Astia / Soft',
    shortCode: 'AS',
    year: '1997',
    author: 'Fujifilm Official',
    category: 'fuji',
    baseFilm: 'Fujichrome Astia 100',
    description: 'Porträttfavorit med krämiga hudtoner, mjukare kontrast och subtila pasteller.',
    contrast: 0.95,
    exposure: 0.08,
    highlights: -0.2,
    shadows: -0.15,
    saturation: 0.96,
    colorMatrix: [
      1.04, -0.02, -0.02,
      0.00, 1.00, 0.00,
      -0.02, 0.02, 1.00
    ],
    wbShift: { r: 0.05, b: -0.03 },
    grainAmount: 0.16,
    grainRoughness: 0.38,
    bloomAmount: 0.18,
    halationAmount: 0.14,
  },
  {
    id: 'nostalgic-negative',
    name: 'Nostalgic Negative',
    shortCode: 'NN',
    year: '1970s',
    author: 'Fujifilm Official',
    category: 'fuji',
    baseFilm: 'American New Color',
    description: 'Bärnstensfärgade varma högdagrar, rika skuggor och vintage 70-talskänsla.',
    contrast: 1.18,
    exposure: 0.02,
    highlights: -0.1,
    shadows: 0.25,
    saturation: 1.05,
    colorMatrix: [
      1.10, 0.02, -0.12,
      -0.02, 1.05, -0.03,
      -0.08, 0.06, 0.88
    ],
    wbShift: { r: 0.10, b: -0.12 },
    grainAmount: 0.26,
    grainRoughness: 0.50,
    bloomAmount: 0.25,
    halationAmount: 0.30,
  },

  // ==========================================
  // 🎬 CINEMA & SVARTVITT (MONOCHROME)
  // ==========================================
  {
    id: 'cinestill-800t',
    name: 'CineStill 800T',
    shortCode: '800T',
    year: 'Cinema',
    author: 'Analog Cinema',
    category: 'cinema-mono',
    baseFilm: 'Kodak Vision3 500T',
    description: 'Nattfilmsestetik med kylig tungsten-balans och distinkt röd halation kring ljuskällor.',
    contrast: 1.24,
    exposure: 0.0,
    highlights: 0.2,
    shadows: 0.35,
    saturation: 1.02,
    colorMatrix: [
      0.90, -0.02, 0.12,
      -0.05, 0.95, 0.10,
      -0.05, 0.00, 1.15
    ],
    wbShift: { r: -0.08, b: 0.15 },
    grainAmount: 0.32,
    grainRoughness: 0.58,
    bloomAmount: 0.30,
    halationAmount: 0.48, // Strong red halation
  },
  {
    id: 'eterna-cinema',
    name: 'Eterna / Cinema',
    shortCode: 'ETN',
    year: '2018',
    author: 'Fujifilm Official',
    category: 'cinema-mono',
    baseFilm: 'Fujicolor Eterna 500T',
    description: 'Filmisk lågmättad profil med mycket mjuk skuggövergång och cinematiska toner.',
    contrast: 0.88,
    exposure: 0.04,
    highlights: -0.3,
    shadows: -0.2,
    saturation: 0.72,
    colorMatrix: [
      0.90, 0.05, 0.05,
      0.02, 0.92, 0.06,
      0.00, 0.10, 0.90
    ],
    wbShift: { r: -0.02, b: -0.04 },
    grainAmount: 0.20,
    grainRoughness: 0.42,
    bloomAmount: 0.22,
    halationAmount: 0.20,
  },
  {
    id: 'bleach-bypass',
    name: 'Bleach Bypass',
    shortCode: 'BYP',
    year: '2020',
    author: 'Fujifilm Official',
    category: 'cinema-mono',
    baseFilm: 'Eterna Bleach Bypass',
    description: 'Rått industriellt uttryck med extrem kontrast, blekt färg och metallisk känsla.',
    contrast: 1.45,
    exposure: -0.08,
    highlights: 0.4,
    shadows: 0.45,
    saturation: 0.35,
    colorMatrix: [
      0.65, 0.25, 0.10,
      0.20, 0.65, 0.15,
      0.15, 0.20, 0.65
    ],
    wbShift: { r: 0.0, b: -0.05 },
    grainAmount: 0.35,
    grainRoughness: 0.60,
    bloomAmount: 0.15,
    halationAmount: 0.20,
  },
  {
    id: 'kodak-tri-x-400',
    name: 'Kodak Tri-X 400',
    shortCode: 'TX',
    year: '1954',
    author: 'Fuji X Weekly',
    category: 'cinema-mono',
    baseFilm: 'Monochrome / Acros',
    description: 'Legendarisk svartvit fotojournalism med djup svärta, rått korn och kompromisslös kontrast.',
    contrast: 1.40,
    exposure: -0.02,
    highlights: 0.25,
    shadows: 0.45,
    saturation: 0.0,
    colorMatrix: [
      0.32, 0.58, 0.10,
      0.32, 0.58, 0.10,
      0.32, 0.58, 0.10
    ],
    wbShift: { r: 0.0, b: 0.0 },
    grainAmount: 0.38,
    grainRoughness: 0.65,
    bloomAmount: 0.14,
    halationAmount: 0.20,
    isMonochrome: true,
    monoFilter: 'none'
  },
  {
    id: 'acros-standard',
    name: 'Acros (S/V)',
    shortCode: 'ACR',
    year: '2006',
    author: 'Fujifilm Official',
    category: 'cinema-mono',
    baseFilm: 'Neopan Acros 100',
    description: 'Legendarisk svartvit emulering med oöverträffad tonalitet och silverlyster.',
    contrast: 1.20,
    exposure: 0.0,
    highlights: 0.15,
    shadows: 0.25,
    saturation: 0.0,
    colorMatrix: [
      0.30, 0.59, 0.11,
      0.30, 0.59, 0.11,
      0.30, 0.59, 0.11
    ],
    wbShift: { r: 0.0, b: 0.0 },
    grainAmount: 0.26,
    grainRoughness: 0.50,
    bloomAmount: 0.14,
    halationAmount: 0.18,
    isMonochrome: true,
    monoFilter: 'none'
  },
  {
    id: 'acros-red',
    name: 'Acros + Röd Filter',
    shortCode: 'ACR-R',
    year: '2006',
    author: 'Fujifilm Official',
    category: 'cinema-mono',
    baseFilm: 'Neopan Acros + Red',
    description: 'Dramatisk svartvit med mörkare himmel, ljusare hud och hög kontrast.',
    contrast: 1.35,
    exposure: -0.05,
    highlights: 0.3,
    shadows: 0.4,
    saturation: 0.0,
    colorMatrix: [
      0.70, 0.25, 0.05,
      0.70, 0.25, 0.05,
      0.70, 0.25, 0.05
    ],
    wbShift: { r: 0.0, b: 0.0 },
    grainAmount: 0.30,
    grainRoughness: 0.52,
    bloomAmount: 0.16,
    halationAmount: 0.22,
    isMonochrome: true,
    monoFilter: 'red'
  }
];

export const DEFAULT_RECIPE = FILM_RECIPES[0]; // Classic Cuban Negative (Osan Bilgi)
